### ISSUE TITLE
TypeError: Cannot read property 'modulePath' of null

### ISSUE THREAD

**Issue by tao7544** [dolymood/webpack-transform-modules-plugin#8]
TypeError: Cannot read property 'modulePath' of null
    at Object.collectTransformModules (\node_modules\webpack-transform-modules-plugin\lib\util.js:29:20)

**Comment by dolymood** [comment]
最新版本，目测的应该是node_modules下pkg不对，建议删除 重新安装

**Comment by dolymood** [comment]
0.4.4 已经修复
